### ISSUE TITLE
String values in attributes that match XML node template string will get replaced when dumping

### ISSUE THREAD

**Issue by Kiisu-Master** [elenakrittik/GodotXML#23]
### Version
GodotXML v2.1.0, Godot 4.2.2.rc2

### Issue
When you add an attribute of type `String` with value `"{children}"` to a node, it gets replaced with the actual string of the nodes children when dumping.

### Expected
The string is saved as an attribute of the node.

**Comment by elenakrittik** [comment]
Thanks for the report! This looks like an bug in Godot, i reported it here: godotengine/godot#89604

If you want an immediate fix, swap lines 178 and 181 here:
https://github.com/elenakrittik/GodotXML/blob/79b43d0d8a2886ccbe6970767acf8bbca13ca846/addons/godot_xml/xml_node.gd#L177-L181
and lines 213 and 216 here:
https://github.com/elenakrittik/GodotXML/blob/79b43d0d8a2886ccbe6970767acf8bbca13ca846/addons/godot_xml/xml_node.gd#L212-L217
in your local copy of GodotXML, this should do it

**Comment by Kiisu-Master** [comment]
Well the `"{children}"` was just a example. Im dealing with user input and it could be any of the templates names.
Im also a bit concerned about what happens when there is `"` in strings passed by user, I haven't tested it yet, but I don't see any escaping in the code rn.

It's not super serious in my case because there isn't really any reason for users to input this kind of string, i was just reading trough the code and wondered what happens if I do it.

I read trough the source code of `String.format` and didn't see clean way to solve the problem. It just loops over the same string, finding the template and replacing it with the content. If the last template added one of the next ones, it will get replaced in the loops.

The solution would probably be to concatenate the string instead of using templates.

**Comment by Kiisu-Master** [comment]
Well i guess my theory about string escaping is confirmed.
I think it would be good if safeguards and escaping were done on the addon side, as that's where i would expect it to happen.
It would be great if the automated tests were added, because this is a project that would greatly benefit from them.
![image](https://github.com/elenakrittik/GodotXML/assets/142301391/0adf5518-8629-4376-9b64-8e877fffcc3c)


```gdscript
func _ready():
	var xml := XMLNode.new()
	
	xml.attributes["attr_one"] = '"attr_two="hello world'
	
	var dump_string := xml.dump_str()
	
	var parsed_xml := XML.parse_str(dump_string).root
	
	assert(not parsed_xml.attributes.has("attr_two"), "Failed to preserve XML node after dumping and parsing.")

```

**Comment by elenakrittik** [comment]
This behavior of `String.format` is, apparently, intentional! I would prefer not to escape format placeholders in the library itself, but i agree that we should handle escaping quotes and other special characters like `&` or angle brackets when (de)serializing. I opened #24 to track this, PR welcome if you want to ;)

**Comment by elenakrittik** [comment]
> Well i guess my theory about string escaping is confirmed.

Yeah, we don't currently escape characters 😅

**Comment by Kiisu-Master** [comment]
> This behavior of `String.format` is, apparently, intentional! I would prefer not to escape format placeholders in the library itself, but i agree that we should handle escaping quotes and other special characters like `&` or angle brackets when (de)serializing. I opened #24 to track this, PR welcome if you want to ;)

The format placeholders problem is a bit more tricky than the string escaping. I can escape the strings i add to XML nodes easily, but i can in no way prevent any placeholder getting replaced, because if i tried to escape these id end up writing a XML file with content that isn't what it should be.
The problem can only be solved on the addon side, while escaping can be done by the lib user.
