### ISSUE TITLE
Character escaping

### ISSUE THREAD

**Issue by elenakrittik** [elenakrittik/GodotXML#24]
We currently don't transform sequences like `&quot` when parsing, nor do we escape characters when dumping.

**Comment by Kiisu-Master** [comment]
There is a `String.xml_escape(escape_quotes: bool)`, and when i add it to the dump functions in the attribute string creation loop by checking if the attribute value is a string it seems to do the job. Should i create a pr?

https://github.com/elenakrittik/GodotXML/blob/79b43d0d8a2886ccbe6970767acf8bbca13ca846/addons/godot_xml/xml_node.gd#L166-L168


````gdscript

	var attribute_value := self.attributes.get(attribute_key)
	if attribute_value is String:
		attribute_value = attribute_value.xml_escape(true)
	attribute_string += '{key}="{value}"'.format({"key": attribute_key, "value": attribute_value})

**Comment by elenakrittik** [comment]
> Should i create a pr?

Yes, PRs always appreciated! Also, do you think calling `xml_escape` just once before returning would work?

**Comment by Kiisu-Master** [comment]
> > Should i create a pr?
> 
> Yes, PRs always appreciated! Also, do you think calling `xml_escape` just once before returning would work?

I don't understand that question...
It only makes sense to escape the value if its a string. If you do it on the whole `attribute_string` it will escape the `"` added for attributes, which would result in a wrong XML node.

**Comment by elenakrittik** [comment]
> > > Should i create a pr?
> > 
> > 
> > Yes, PRs always appreciated! Also, do you think calling `xml_escape` just once before returning would work?
> 
> I don't understand that question... It only makes sense to escape the value if its a string. If you do it on the whole `attribute_string` it will escape the `"` added for attributes, which would result in a wrong XML node.

Oh right, sorry. That was a dumb thought from me
